/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BaseGame;

import java.util.ArrayList;
import java.util.List;

import BaseGame.CardLogic.*;
import BaseGame.Cards.*;
import BaseGame.Rectangles.CardRectangle;
import BaseGame.Rectangles.Rectangle;
import processing.core.PApplet;
import processing.core.PImage;
import processing.data.JSONObject;

public class App extends PApplet {

    public DeckHandler curGameHandler = new HomePage(this);
    private DeckHandler queuedGameHandler;
    public int numPlayers = 0;
    /** 0 for the host, -1 for an uninitialized player */
    public int thisPlayerNumber = -1;
    public int curPlayerNumber = 0;
    public int minPlayerCount;

    public float scaleFactor;
    /** Default width of a card */
    public int defaultWidth; // = 100
    /** Default height of a card */
    public int defaultHeight; // = 145
    /** Default horizontal spacing for neighbor cards */
    public int defaultHSpacing; // = 15
    /** Default vertical spacing for selected cards */
    public int defaultVSpacing; // = 40
    
    public PImage imageList[];
    /** Index of the card back in imageList */
    public int cardBackIndex;

    public Player thisPlayer;
    public List<Player> playerList = new ArrayList<Player>();

    public DiscordBot bot;


    @Override
    public void settings() {
        fullScreen();
    }

    @Override
    public void setup() {
        background(0, 150, 0);
        frameRate(60);
        noLoop();

        Rectangle.app = this;

        scaleFactor = min((float) displayWidth / 1920, (float) displayHeight / 1080);
        defaultWidth = (int) (100 * scaleFactor);
        defaultHeight = (int) (145 * scaleFactor);
        defaultHSpacing = (int) (15 * scaleFactor);
        defaultVSpacing = (int) (40 * scaleFactor);

        imageList = new PImage[13 * 4 + 3];
        for (Suit s : Suit.values()) {
            imageList[s.getValue()] = loadImage("app/src/main/resources/Poker Cards PNG/ace_of_" + s.toString() + ".png");

            for (int i = 1; i < 10; i++)
                imageList[i * 4 + s.getValue()] = loadImage(
                        "app/src/main/resources/Poker Cards PNG/" + (i + 1) + "_of_" + s.toString() + ".png");

            imageList[10 * 4 + s.getValue()] = loadImage(
                    "app/src/main/resources/Poker Cards PNG/jack_of_" + s.toString() + "2.png");
            imageList[11 * 4 + s.getValue()] = loadImage(
                    "app/src/main/resources/Poker Cards PNG/queen_of_" + s.toString() + "2.png");
            imageList[12 * 4 + s.getValue()] = loadImage(
                    "app/src/main/resources/Poker Cards PNG/king_of_" + s.toString() + "2.png");
        }
        cardBackIndex = 54;
        imageList[13 * 4 + 2] = loadImage("app/src/main/resources/Poker Cards PNG/card_back_red.png");
        imageList[13 * 4] = loadImage("app/src/main/resources/Poker Cards PNG/red_joker.png");
        imageList[13 * 4 + 1] = loadImage("app/src/main/resources/Poker Cards PNG/black_joker.png");
        JSONObject configObj = loadJSONObject("config.json");

        String user = configObj.getString("user");
        DiscordBot.initializeBot(this, user);
    }

    public void hostGame(String host, String game) {
        thisPlayerNumber = 0;
        thisPlayer = new Player(host, numPlayers++);
        playerList.add(thisPlayer);
        queueGame(game);
        queuedGameHandler.initializeDeck();
        minPlayerCount = queuedGameHandler.minPlayerCount;
    }

    public void queueGame(String game) {
        switch(game){
            case "pontinho":
                queuedGameHandler = new PontinhoHandler(this);
                break;
            default:
                System.out.println("Invalid game");
                exit();
        }
    }

    public void addPlayer(String player){
        playerList.add(new Player(player, numPlayers++));
    }

    public String getQueuedStartingDeck() {
        return queuedGameHandler.startingDeck;
    }

    public boolean waitingForGame() {
        return queuedGameHandler == null;
    }

    public void startGame(String startingDeck) {
        curGameHandler = queuedGameHandler;
        curGameHandler.initializeDeck(startingDeck);
        curGameHandler.setup();
        loop();
    }

    public CardRectangle pickedUpRect;
    public float xOffset;
    public float yOffset;

    @Override
    public void mouseClicked() {
        if(curGameHandler.handleMouseClick(mouseX, mouseY)) {
            nextTurn();
            bot.processMove(curGameHandler.encodeGameState());
        }
    }

    public boolean nextTurn() {
        return (curPlayerNumber = (curPlayerNumber + 1) % numPlayers) == thisPlayerNumber;
    }

    public void makeMove(String nextMove) {
        nextTurn();
        curGameHandler.decodeGameState(nextMove);
    }

    /**
     * Picks up a rectangle to be moved if necessary
     */
    @Override 
    public void mousePressed() {
        curGameHandler.handleMousePress(mouseX, mouseY);
    }

    @Override
    public void mouseReleased() {
        curGameHandler.handleMouseRelease(mouseX, mouseY);
    }

    @Override
    public void mouseDragged() {
        curGameHandler.handleMouseDrag(mouseX, mouseY);          
    }

    @Override
    public void draw() {
        background(0, 150, 0);
        curGameHandler.draw();
    }

    public static void main(String[] args) {
        String PAppletArgs[] = {"--present"};
        PApplet.main("BaseGame.App", PAppletArgs);
    }

    public App(){}

    public App(int x) {
        surface = initSurface();
        sketchPath();
        handleDraw();
        setup();
        noLoop();
    }

    public String playerListToString() {
        String res = "";
        for(Player p : playerList) {
            res += p.encodePlayer() + "\n";
        }
        return res;
    }

    public void makePlayerList(String stringList, String user) {
        String[] playerNames = stringList.split("\n");
        numPlayers = playerNames.length;
        for(int i = 0; i < numPlayers; i++) {
            String name = playerNames[i].substring(10);
            playerList.add(new Player(name, i));
            if(playerList.get(i).isPlayer(user)) {
                thisPlayerNumber = i;
                thisPlayer = playerList.get(i);
            }
        }
    }

    public boolean removePlayer(String name) {
        for(int i = 0; i < numPlayers; i++) 
            if(playerList.get(i).isPlayer(name)) {
                playerList.remove(i);
                return true;
            }
        return false;
    }

    public void reset() {
        curGameHandler = new HomePage(this);
        queuedGameHandler = null;
        numPlayers = 0;
        thisPlayerNumber = -1;
        thisPlayer = null;
        playerList = new ArrayList<Player>();
        noLoop();
    }

    
}

